trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.7
    architecture: 'x64'

- task: DownloadSecureFile@1
  inputs:
    name: configFile
    secureFile: config.json
- script: echo "Printing the secure file path" 
- script: cp $(Agent.TempDirectory)/config.json $(Build.SourcesDirectory)/config.json

- task: CondaEnvironment@1
  displayName: 'Create Conda Environment '
  inputs:
    createCustomEnvironment: true
    environmentName: knowledge_distillation
    packageSpecs: 'python=3.7.3'
    updateConda: false
- script: |
    pip install --user azureml-sdk
  displayName: 'Install prerequisites'

- task: AzureCLI@1
  displayName: 'Build and Publish Teacher Pipeline'
  inputs:
    azureSubscription: 'serviceConnection'
    scriptLocation: inlineScript
    inlineScript: 'python pipeline_teacher.py'

- task: AzureCLI@1
  displayName: 'Build and Publish Student Pipeline'
  inputs:
    azureSubscription: 'serviceConnection'
    scriptLocation: inlineScript
    inlineScript: 'python pipeline_student.py'

- task: AzureCLI@1
  displayName: 'Run Published Pipelines'
  timeoutInMinutes: 120
  inputs:
    azureSubscription: 'serviceConnection'
    scriptLocation: inlineScript
    inlineScript: 'python run_pipelines.py'

- task: AzureCLI@1
  displayName: 'Deploy Webservice'
  inputs:
    azureSubscription: 'serviceConnection'
    scriptLocation: inlineScript
    inlineScript: 'python deploy_aci.py'
  

